buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        // Use a compatible Android Gradle Plugin version. Adjust if your project needs a different one.
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
